version: '2'

services:
    gw:
        image: jrgensen/gateway
        restart: always
        environment:
            PROXY_MAPPINGS: >
                nats:nats-streaming-console:8282
                nats-monitor:nats-streaming-server:8222
                redis:redis-commander:8081
        ports:
        - 80

    scan-app:
        image: nathejk/scan-app
        build: ../scan-app
        volumes:
        - ".:/var/www"
        environment:
            STAN_DSN: stan://nats-streaming-server/test-cluster
            DB_DSN: mysql://nathejk:kodeord@mysql/scan
            MONOLITH_DB_DSN: mysql://nathejk:kodeord@local.pnorental.com:13306/nathejk2018

    mysql:
        image: mariadb:10.0
        restart: always
        environment:
            MYSQL_DATABASE: scan
            MYSQL_USER: nathejk
            MYSQL_PASSWORD: kodeord
            MYSQL_ROOT_PASSWORD: ib
            TZ: Europe/Copenhagen

    nats-streaming-server:
        image: nats-streaming:0.16.0
        restart: always

    nats-streaming-console:
        image: jrgensen/nats-streaming-console
        restart: always
        environment:
            STAN_URL: nats://nats-streaming-server:4222
            STAN_MONITOR_URL: http://nats-streaming-server:8222
            STAN_CLUSTER: test-cluster


