version: '2'

services:
    gw:
        image: jrgensen/gateway
        restart: always
        environment:
            PROXY_MAPPINGS: >
                nats:nats-streaming-console:8282
                nats-monitor:nats-streaming-server:8222
                redis:redis-commander:8081
        ports:
        - 80

    scan-app:
        image: nathejk/scan-app
        build: ../scan-app
        volumes:
        - ".:/var/www"
        environment:
            STAN_DSN: stan://dev.nathejk.dk:4222/nathejk
            DB_DSN: mysql://nathejk:kodeord@mysql/scan
            MONOLITH_DB_DSN: mysql://nathejk:kodeord@dev.nathejk.dk:13306/nathejk2018

    mysql:
        image: mariadb:10.0
        restart: always
        environment:
            MYSQL_DATABASE: scan
            MYSQL_USER: nathejk
            MYSQL_PASSWORD: kodeord
            MYSQL_ROOT_PASSWORD: ib
            TZ: Europe/Copenhagen

